name: flutter_translator
description: Flutter Translator is a package use for in-app localization with json file. More easier and faster to implement. This package is inspired by the flutter_localizations itself.
version: 0.0.11
homepage: https://github.com/channdara/flutter_translator

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/flutter_translator/assets/language_name.json

  plugin:
    platforms:
      ios:
        pluginClass: FlutterTranslatorPlugin
      android:
        pluginClass: FlutterTranslatorPlugin
        package: com.mastertipsy.flutter_translator