name: flutter_translator
description: Flutter Translator is a package use for in-app localization with json file and map. More easier and faster to implement and inspired by the flutter_localizations itself.
version: 0.1.4
homepage: https://github.com/channdara/flutter_translator

# check package before publish: flutter pub publish --dry-run
# publish package: flutter pub publish

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterTranslatorPlugin
      android:
        pluginClass: FlutterTranslatorPlugin
        package: com.mastertipsy.flutter_translator
      web:
        pluginClass: FlutterTranslatorWeb
        fileName: src/translator_web.dart